name: Androidbuild
on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant rights
        run: chmod +x build.gradle

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Build Release APK
        id: buildRelease
        run: ./gradlew assembleRelease

      //添加这个打包好的APK可以进行本地下载
      - uses: actions/upload-artifact@v2
        name: upload build output
        with:
         name: tvbox
         path: ${{ github.workspace }}/app/build/outputs/apk/release

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.besttextonphoto.addbesttext
          releaseFiles: app/build/outputs/apk/release/app-release.apk
          track: internal
